Fix custom deps not working on HA 2021.07
home-assistant/addons-development pull request #20
Opened 2021-07-09 15:31 UTC by marciogranzotto

2021.07 seems to use python 3.9

2021-07-12 05:26 UTC, ludeeus requested changes
Please update the version <https://github.com/home-assistant/addons-development/blob/master/custom_deps/config.json#L3> and the CHANGELOG.md file to reflect the changes made here.

2021-07-18 17:04 UTC, marciogranzotto commented
@ludeeus done!

2021-07-26 11:02 UTC, ludeeus requested changes

2021-07-26 11:02 UTC, ludeeus commented on custom_deps/CHANGELOG.md
> +- Update Python 3.9
```suggestion
- Update Python to 3.9
```

2021-08-12 18:35 UTC, ludeeus commented on custom_deps/CHANGELOG.md
> +
```suggestion
- Update Python to 3.9
- Set minimum Core version to 2021.7.0
```

2021-08-12 18:35 UTC, ludeeus commented on custom_deps/config.json
> +  "homeassistant", "2021.7.0",
```suggestion
  "homeassistant": "2021.7.0",
```

2021-08-12 18:37 UTC, merged